export const GET_ALL_LIST = 'GET_ALL_LIST';
export const GET_ALL_RECORD = 'GET_ALL_RECORD';
export const SAVE_ALL_RECORD = 'SAVE_ALL_RECORD';
export const DELETE_ALL_RECORD = 'DELETE_ALL_RECORD';
export const RECORD_ALL_CLEAR_STATUS = 'RECORD_ALL_CLEAR_STATUS';
export const RECORD_ALL_CLEAR_FORM_DATA = 'RECORD_ALL_CLEAR_FORM_DATA';