export const GET_LIST = 'GET_LIST';
export const GET_RECORD = 'GET_RECORD';
export const SAVE_RECORD = 'SAVE_RECORD';
export const DELETE_RECORD = 'DELETE_RECORD';
export const RECORD_CLEAR_STATUS = 'RECORD_CLEAR_STATUS';
export const RECORD_CLEAR_FORM_DATA = 'RECORD_CLEAR_FORM_DATA';